use_frameworks!

target 'SwiftTableSpaces_Example' do
  pod 'SwiftTableSpaces', :path => '../'

  target 'SwiftTableSpaces_Tests' do
    inherit! :search_paths

#    pod 'SwiftTableSpaces', :path => '../'
    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
